USE recipe_sharing;
INSERT INTO recipes (recipe_name, cuisine, recipe_description, ingredients, recipe_method) VALUES 
# Recipe taken from https://www.jamieoliver.com/recipes/pasta-recipes/a-killer-mac-n-cheese/
('Mac & Cheese', 'American', 'Beautifully gooey and full-on, in your face cheesy', '10 cloves of garlic, 45g butter, 3 heaped tbsps plain flour, 6 bay leaves, 1l semi-skimmed milk, 600g dried macaroni, 8 tomatoes, 150g cheddar cheese, 100g parmesan cheese, few sprigs of fresh thyme', 'Peel and slice garlic. In a pan, salt the water on a boil and melt the butter before adding the flour - it should become paste-like. Add the garlic to the paste and keep stirring until golden and garlic is sticky. Add bay leaves and slowly add in the milk to ensure a smooth sauce. Add pasta to the pan of salted water and cook until ready. Chop the tomatoes, grate both cheeses, beofre draining the pasta and adding to the salted water. Stir in the grated cheeses, chopped tomatoes and half the thyme sprigs and place in an oven dish at Gas mark 7.'),
# Recipe taken from https://realfood.tesco.com/recipes/sweet-potato-and-pepper-enchiladas.html
('Sweet potato & pepper enchiladas', 'Mexican', 'Vegetarian-friendly, loaded with Cajun flavour and plenty of veg', '2 sweet potatoes diced, 2 small onions diced, 2 tbsp cajun seasoning, 400g tin chopped tomatoes, 1 peeled garlic clove, 10g fresh coriander - 5g chopped & 5g with their leaves picked, 4 tortilla wraps, 120g grated cheddar, 250g sweet & crunchy salad pack', 'Preheat over at Gas mark 7. Pour sweet potatoes, peppers and onions on a baking tray, beofre drizzing with 1.5 tbsp of oil and 1 tbsp of cajun seasoning. Roast for 20-25 minutes until tender and lightly golden. Blitz the tomatoes, chilli, garlic and 1tbsp of cajun seasoning, before pouring into a saucepan. Simmer over medium heat for 5 minutes until thickened slightly. Mix the roasted veg in a bowl with chopped coriander and half the tomato sauce. Spoon onto tortilla wraps in a line and tightly roll up, before transferring onto greased baking dish in a single layer. Pour on the remaining sauce and scatter the cheese; then bake for 10-15 minutes until hot and bubbling.'),
# Recipe taken from https://realfood.tesco.com/recipes/pork-teriyaki-rice-and-broccoli.html
('Pork teriyaki, rice and broccoli', 'Japanese', 'Marinated pork in soy, ginger, honey, mustard. Served with broccoli and fluffy rice', '3tbsp light soy sauce, 20g finely grated ginger, 2 crushed garlic cloves, 1tbsp dijon mustard, 2tbsp honey, 500g diced pork, 300g long-grain rice, 1/2tbsp vegetable oil, 1 broccoli - cut into florets, 2tbsp crispy onions', 'Combine soy, ginger, mustard and honey in a bowl and add the pork to coat, before leaving to marinate for 15 minutes at room temperature or for up to 24hrs. Cook the rice. Heat the oil in a pan over a high heat and dry the pork along with any marinade from the bowl. Stir fry for 10-12 minutes until pork is cooked through and the marinade is sticky and coats the pork. Boil the broccoli in pan of salted water for 6-8 minutes until the stems are tender. Drain the broccoli and rice when cooked. Fluff up rice with a fork and spoon into a bowl and place the teriyaki pork and broccoli on top.'),
# Recipe taken from https://www.sainsburysmagazine.co.uk/recipes/mains/pasta-frittata
('Pasta frittata', 'Italian', 'Got leftover pasta, protein or cheese? Substitute these for pancetta and mozzarella and enjoy with salad!', '100g dried spaghetti (or any leftover pasta), 160g diced pancetta or bacon (substitute these for the leftover protein), 8 medium eggs, 60g grated parmesan (substitute for thhe leftover cheese), 1 x 125g mozzarella ball', 'Cook the spaghetti or pasta, drain, rise with cold water and drain again (or 300g leftover cooked pasta). Mix the spaghetti/pasta with 1tbsp of olive oil and leave to cool. Heat 1tbsp of olive oil in a pan and fry the pancetta/bacon until crisp and set aside on a plate. In a large bowl, whisk the eggs, 60g grated parmesan, the mozzarella ball and the cooled pasta and pancetta/bacon. Season and mix with black pepper and salt. Reheat the pancetta dat in the pan and pour the mixture into the pan. Cover with a lid or baking tray and cook gently for 15 minutes or until the bottom is golden and the top is set. Flip with the help of a plate and cook for a further 5 minutes, uncovered, until golden underneath.');
